### ISSUE TITLE
Observations for common problems

### ISSUE THREAD

**Issue by zner0L** [tweaselORG/docs.tweasel.org#5]
- [ ] Test device and host need to be on the same network and able to talk to each other

**Comment by baltpeter** [comment]
* [ ] If you're seeing an error like this, you need `type: module`:

```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Transform failed with 1 error:
/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/temp-dir/index.js:4:27: ERROR: Top-level await is currently not supported with the "cjs" output format
    at failureErrorWithLog (/usr/lib/node_modules/tsx/node_modules/esbuild/lib/main.js:1575:15)
    at /usr/lib/node_modules/tsx/node_modules/esbuild/lib/main.js:814:29
    at responseCallbacks.<computed> (/usr/lib/node_modules/tsx/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/usr/lib/node_modules/tsx/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/usr/lib/node_modules/tsx/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: '/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/temp-dir/index.js',
        length: 5,
        line: 4,
        lineText: 'const temporaryDirectory = await fs.realpath(os.tmpdir());',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Top-level await is currently not supported with the "cjs" output format'
    }
  ],
  warnings: []
}

Node.js v18.16.1
```

```
/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/andromatic/dist/index.js:37
        $9c1753d8bf94ff15$var$locateJavaHome(options || {}, (err, javaHomes)=>{
        ^


TypeError: $9c1753d8bf94ff15$var$locateJavaHome is not a function
    at <anonymous> (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/andromatic/dist/index.js:37:9)
    at new Promise (<anonymous>)
    at $9c1753d8bf94ff15$export$c149ac4f84685796 (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/andromatic/dist/index.js:36:62)
    at $054ab01bb585d84a$var$ensureJavaHome (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/andromatic/dist/index.js:341:39)
    at $054ab01bb585d84a$export$787d9c481e759193 (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/andromatic/dist/index.js:372:28)
    at $054ab01bb585d84a$export$957f9a3903c54a5e (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/andromatic/dist/index.js:531:27)
    at Object.ensureDevice (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/appstraction/dist/index.js:713:13)
    at <anonymous> (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/run.ts:25:5)

Node.js v18.16.1
```

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/cyanoacrylate/dist/index.js from /home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/index.js not supported.
Instead change the require of /home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/node_modules/cyanoacrylate/dist/index.js in /home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/benni/coding/JS/tweasel/experiments/aclum-location-analysis.tmp/index.js:1:28) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by zner0L** [comment]
- [ ] You need exactly Node 18
